#!/bin/bash



# Functions for Midnight Commander helper scripts



# Config Parameters

export MC_THUMBNAILS="dir"      # dir - generate TN for whore base dir of a file opened by mcopen
                                # file  - generate only for a chosen file
                                # no    - do not generate thumbnails

export MC_NOTIFY="true"         # Should script send desktop notfications?

# Desktop searh parameters

export MC_SEARCH_APPS="true"
export MC_SEARCH_COMMANDS="true"
export MC_SEARCH_RECOLL="true" # If false, standard file find will be performed
export MC_RECOLL_MAX="50" # Recoll results limit for limited search
export MC_WWW_FIREFOX="false" # Search WWW history from Firefox
export MC_WWW_FIREFOX_MAX="100"



TF_UrlDecode () {

    local url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"

} #TF_UrlDecode
export -f TF_UrlDecode







TF_UrlEncode () {
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            '/') printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
} #TF_UrlEncode
export -f TF_UrlEncode




TF_htmlEscape () {
    local s
    s=${1//&/&amp;}
    s=${s//</&lt;}
    s=${s//>/&gt;}
    s=${s//'"'/&quot;}
    printf -- %s "$s"
} #TF_htmlEscape
export -f TF_htmlEscape 






MCF_FileName () {

    SPATH="$1"

    [ ! -d "$SPATH" ] && return 1

    shift
    SFILE="$1"

    shift
    EXT="$1"

    SBASE="${SFILE##*/}"
    BASE="${SBASE%.*}"

    if [ "$EXT" = "" ]; then
	if [[ "$SBASE" == *"."* ]]; then
	    EXT=".${SBASE##*.}"
	else
	    EXT=""
	fi
    else
	EXT=".$EXT"
    fi

    if [[ -f "$SPATH/$BASE""$EXT" || -d "$SPATH/$BASE""$EXT" || -L "$SPATH/$BASE""$EXT" ]] ; then
	I="1"
	while [ -f "$SPATH/$BASE ($I)""$EXT" ]; do
	    I="$(($I+1))"
	done
	SNAME="$BASE ($I)$EXT"
    else
	SNAME="$BASE""$EXT"
    fi

    printf %s "$SNAME"

} #MCF_FileName
export -f MCF_FileName




#Error notification
TF_ErrCheck () {

    if [ "$?" != "0" ]; then
	/usr/bin/notify-send -t 0 -i error "$1" > /dev/null 2>&1 &
	return 0
    else
	if [ "$2" != "" ]; then
	    if [ "$3" != "" ]; then
		/usr/bin/notify-send -i "$3" "$2" > /dev/null 2>&1 &
	    else
		/usr/bin/notify-send "$2" > /dev/null 2>&1 &
	    fi
	fi
	return 1
    fi

} #TF_ErrCheck
export -f TF_ErrCheck




TF_ThumbnailPath () {
    TN="file://$(TF_UrlEncode "$@")"
    TN="$HOME/.cache/thumbnails/normal/$(printf %s "$TN" | /usr/bin/md5sum).png"
    TN="${TN//  -/}"
    printf %s "$TN"
} #TF_ThumbnailPath
export -f TF_ThumbnailPath





if [[ "$1" == "filename" ]]; then
    shift
    MCF_FileName "$1" "$2" "$3"
fi

